Repository kloud-community/kloud-bot, pull requests merged in 2023-12, with the labels that each got.

#3 build: Add linter / formatter and local hooks
  .husky/pre-commit
  biome.json
  bun.lockb
  lint-staged.config.js
  package.json
  src/index.ts
Labels: area: devexp, type: new

#4 chore: add a issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: area: docs, type: new

#5 chore: add new CI for checking styles
  .github/workflows/check.yml
  package.json
Labels: area: devexp, type: new

#15 feat: define interface and types
  bun.lockb
  package.json
  src/events/type.ts
  src/features/interface.ts
  tsconfig.json
Labels: area: bot, type: new
